spring:
  mustache:
    suffix: .html
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    initialization-mode: always